server {
    listen 80;
    server_name localhost;

    # Carpeta donde se encuentran los archivos estáticos de React
    root /usr/share/nginx/html;
    index index.html;

    # Configuración para soportar el enrutamiento de SPA (React Router)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy inverso para las peticiones a la API del backend
    location /api/ {
        proxy_pass http://backend:3001;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}
